### ISSUE TITLE
Getting error: cURL error 60: Peers certificate issuer has been marked as not trusted by the user

### ISSUE THREAD

**Issue by subhojit777** [mglaman/authnet#28]
I am getting error: _cURL error 60: Peer&#039;s certificate issuer has been marked as not trusted by the user_ during payment transaction.

After reading I figured that Authorize.net has updated its POST URLs - using new trusted certificate, but this library is still using the URL using the distrusted certificate.

**Comment by mglaman** [comment]
See c819c2185d3085d5d87e858a76d475dda6d9cf48 and 44f2c578ddd5d3a07224651ed7080524eda8cc03. Update to latest release.
